INSERT INTO address (city, country, pin_code, street, house_number) VALUES
                                                                        ('New York', 'USA', 10001, '5th Ave', 100),
                                                                        ('Los Angeles', 'USA', 90001, 'Sunset Blvd', 200),
                                                                        ('Chicago', 'USA', 60601, 'Michigan Ave', 300),
                                                                        ('Houston', 'USA', 77001, 'Main St', 400),
                                                                        ('Phoenix', 'USA', 85001, 'Camelback Rd', 500),
                                                                        ('Philadelphia', 'USA', 19101, 'Market St', 600),
                                                                        ('San Antonio', 'USA', 78201, 'Broadway', 700),
                                                                        ('San Diego', 'USA', 92101, 'Harbor Dr', 800),
                                                                        ('Dallas', 'USA', 75201, 'Elm St', 900),
                                                                        ('San Jose', 'USA', 95101, 'Santa Clara St', 1000),
                                                                        ('Austin', 'USA', 73301, 'Congress Ave', 1100),
                                                                        ('Jacksonville', 'USA', 32099, 'Bay St', 1200),
                                                                        ('Fort Worth', 'USA', 76101, 'Lancaster Ave', 1300),
                                                                        ('Columbus', 'USA', 43085, 'High St', 1400),
                                                                        ('Charlotte', 'USA', 28201, 'Tryon St', 1500),
                                                                        ('San Francisco', 'USA', 94101, 'Market St', 1600),
                                                                        ('Indianapolis', 'USA', 46201, 'Washington St', 1700),
                                                                        ('Seattle', 'USA', 98101, 'Pike St', 1800),
                                                                        ('Denver', 'USA', 80201, 'Colfax Ave', 1900),
                                                                        ('Washington', 'USA', 20001, 'Pennsylvania Ave', 2000);

